# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: python-lint
      uses: CyberZHG/github-action-python-lint@0.0.2
    - name: Check HTML
      uses: chabad360/htmlproofer@master
      with:
        directory: "email_customer"

